### ISSUE TITLE
Suggestion to define JSON representation of DCNC CTT

### ISSUE THREAD

**Issue by ygonno** [ISDCF/registries#158]
Not sure if this is a right place. I would suggest to define JSON schema to represent DCNC CTT for internal processing (parsing or serializing) and exchanging CTT.

For example, a sample CTT from DCNC website:

MovieTitle_TLR-1-Temp-RedBand-Chain-3D-4Ol-48-DVis_F-133_ EN-EN-OCAP_US-GB_51-HI-VI-IAB-Dbox_2K_ST_20190103_Facility_IOP-3D_OV

can be serialized in a JSON format as:

`{
    "FilmTitle": "MovieTitle",
    "ContentType": {
        "code": "TLR",
        "version": 1
    },
    "ContentTypeModifiers": [
        "Temp", "RedBand", "Chain", "3D", "4fl", "48", "DVis"
    ],
    "ProjectorAspectRatio": {
        "code": "F",
        "value": 133
    },
    "Language": {
        "audio": "EN",
        "text": "EN",
        "caption": "OCAP"
    },
    "TerritoryRating": {
        "territory": "US",
        "rating": "GB"
    },
    "AudioType": {
        "channel": "51",
        "option": [
            "HI", "VI", "IAB", "Dbox"
        ]
    },
    "Resolution": "2K",
    "Studio": "ST",
    "Date": "20190103",
    "Facility": "Facility",
    "Standard": "IOP",
    "PackageType": "OV"
}`

**Comment by jamiegau** [comment]
Due to the ad hoc nature of the DCNC, it's extremely difficult to reliably
map.  Many ISDCF members will go on about how DCNC is only really an
informative presentation of what's in the CPL, and not really something
that you should rely on. (For automation etc)

But in terms of turning it into JSON, clairmeta already does a decent job
of doing this based on the "PROBE" option you can pass to the tool.
Based on what tools are available (asdcplib, and other tools) it will
return a lot of detail.  As part of this a DCNC parser is part of this
PROBE process and based on this will return a python dict or, via command
like, JSON or XML version of that Object.

It's open source and has had a lot of time put into it, so it is likely the
closest you're going to get to what you're after.
More info:
https://github.com/Ymagis/ClairMeta <https://bitli.pro/11pYm_e79266e5>

Example use:

python3 -m clairmeta.cli probe -type dcp path/to/dcp
python3 -m clairmeta.cli probe -type dcp path/to/dcp -format json > dcp.json
python3 -m clairmeta.cli probe -type dcp path/to/dcp -format xml > dcp.xml


Regards,
James Gardiner
[m] +61 4 12 997011

CineTechGeek
Suite 129, 9 Hall Street,
Port Melbourne, VIC 3207
[p] +61 3 9686 5415

www.digitall.net.au <https://bitli.pro/11pYn_907da531>  --
www.finishingroom.com.au <https://bitli.pro/11pYo_f6854d3f> --
www.clubmovie.com.au <https://bitli.pro/11pYp_0d8887c0> --
www.cinetechgeek.com <https://bitli.pro/11pYq_450256fb>

**Comment by ygonno** [comment]
Unfortunately, to the best of my knowledge, only a few facilities are following the DCNC in Japan although the Japanese translation of DCNC is getting popular gradually. I'm trying to help somehow to bring some order or consistency in the daily operation.

I see https://github.com/Ymagis/ClairMeta/blob/develop/clairmeta/utils/isdcf.py is trying to check the naming against the DCNC.

I was hoping a naming/validation service could be provided through a web form. I will make some more research on how to make this happen. Serializing CTT in JSON was not my primary objective.

Thanks,
