### ISSUE TITLE
Move to version 1.0.0

### ISSUE THREAD

**Issue by palemieux** [ISDCF/registries#59]
The project is out of beta and in use by ISDCF

**Comment by palemieux** [comment]
@radford-for-smpte @SteveLLamb Does revving the project to 1.0.0 have any impact on the dependent registries-site and registries-server projects?

**Comment by radford-for-smpte** [comment]
Not in registries-server. It only cares about schema versions, not the package version.

**Comment by SteveLLamb** [comment]
To that point... When revving schema versions, we don't have a mechanism at present to alert us that the build file on the registries-site needs to be updated.

**Comment by radford-for-smpte** [comment]
Yes, the issue is that `registries-site` employs a `cron` to stay synced with the upstream registry, which is good for data changes, but not good for unexpected schema changes. 

`registries-server` in contrast, specifically distinguishing between data changes and schema changes when it pulls in changes from the upstream `registries` repo.

Need to think about what the right answer is. Perhaps at a bare minimum, `registries-site` to refuse to pull in updates if they consist of schema changes.

**Comment by SteveLLamb** [comment]
Yep

> Need to think about what the right answer is. Perhaps at a bare minimum, `registries-site` to refuse to pull in updates if they consist of schema changes

Yep, aware of the cron, I was just pointing it out. I created an issue on that side with the same basic idea as you noted.
